    - name: Copy secure SSH config
      copy:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
        
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
  
    - name: Generate SSH key
      shell: ssh-keygen -b 4096 -t rsa -f /root/.ssh/id_rsa -q -N ""
      args:
        creates: /root/.ssh/id_rsa
        
    - name: Fetch SSH public key
      fetch: 
        src: /root/.ssh/id_rsa.pub
        dest: "{{ local_pubkey_file }}"
        flat: yes


