# Ansible playbook to configure a machine as a hadoop node
#
# Expected input variables
#   master_node_fqdn : The FQDN of master node running HDFS name node and YARN ResourceManager.
#   worker_node_fqdn : The FQDN of worker node running HDFS data node and YARN NodeManager. Not required while provisioning master node.
#   local_pubkey_file : Local file path where target's public key file should be downloaded and stored.
---
- hosts: all

  vars:
    data_device: /dev/sdc
    data_mount: /mnt/dfs
    
    hadoop_distribution: ./hadoop-2.7.0.tar.gz
    hadoop_install_path_parent: /opt
    hadoop_install_path: /opt/hadoop-2.7.0
    
    hdfs_url: "hdfs://{{master_node_fqdn}}:9000"
    hdfs_name_dir: "{{data_mount}}/name"
    hdfs_data_dir: "{{data_mount}}/data"
  
  tasks:
    - name: Install required packages
      apt: name={{ item }} state=latest update_cache=no dpkg_options=force-confnew,force-confask
      with_items:
        - openjdk-7-jre-headless
      become: yes
      
    - name: Install Hadoop distribution if it isn't already
      unarchive: copy=yes creates={{hadoop_install_path}} src={{hadoop_distribution}} 
            dest={{hadoop_install_path_parent}} owner=root group=root
      become: yes
      
    - name: Set JAVA_HOME in hadoop-env.sh
      lineinfile: dest={{hadoop_install_path}}/etc/hadoop/hadoop-env.sh regexp='^export JAVA_HOME=.*$'
            line='export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre' state=present

    - name: Set HADOOP_CONF_DIR in hadoop-env.sh
      lineinfile: dest={{hadoop_install_path}}/etc/hadoop/hadoop-env.sh regexp='^export HADOOP_CONF_DIR=.*$'
            line='export HADOOP_CONF_DIR={{hadoop_install_path}}/etc/hadoop' state=present
    
    - name: Set HADOOP_HOME in hadoop-env.sh
      lineinfile: dest={{hadoop_install_path}}/etc/hadoop/hadoop-env.sh regexp='^export HADOOP_HOME=.*$'
            line='export HADOOP_HOME={{hadoop_install_path}}' insertbefore='^export HADOOP_CONF_DIR=.*$' state=present

    - name: Set HADOOP_PREFIX_DIR in hadoop-env.sh
      lineinfile: dest={{hadoop_install_path}}/etc/hadoop/hadoop-env.sh regexp='^export HADOOP_PREFIX_DIR=.*$'
            line='export HADOOP_PREFIX_DIR={{hadoop_install_path}}' insertbefore='^export HADOOP_CONF_DIR=.*$' state=present


      
            
